### PR TITLE
Added test for one arg

### PR DESCRIPTION
**Pull request by FelixDavidson**
#1 Adds test for functions with one parameter.

### CODE REVIEW

**Review by christianscott — CHANGES_REQUESTED** [review]
Hi Felix, thanks for contributing! Nitpicking, but if you change the name of the lambda to `id` or something I'll accept the pr

**Comment by FelixDavidson** [comment]
Alright I changed it.

**Comment by christianscott** [comment]
Thanks, you forgot to change it on the next line :)

**Comment by FelixDavidson** [comment]
My bad. Now it should be right.

**Review by christianscott — APPROVED** [review]

**Pull request merged**
